# Generated by Django 4.2.16 on 2024-10-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alldata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "database_id",
                    models.CharField(
                        blank=True, db_column="Database_ID", max_length=255, null=True
                    ),
                ),
                ("data_id", models.IntegerField(blank=True, db_column="ID", null=True)),
                (
                    "gene_type",
                    models.CharField(
                        blank=True, db_column="Gene_Type", max_length=255, null=True
                    ),
                ),
                ("tax_id", models.IntegerField(blank=True, null=True)),
                (
                    "gene_summary",
                    models.TextField(blank=True, db_column="Gene_summary", null=True),
                ),
                (
                    "map_location",
                    models.CharField(
                        blank=True, db_column="Map_Location", max_length=255, null=True
                    ),
                ),
                (
                    "org_name",
                    models.CharField(
                        blank=True, db_column="Org_name", max_length=255, null=True
                    ),
                ),
                (
                    "taxonomic_groups",
                    models.CharField(
                        blank=True,
                        db_column="Taxonomic_Groups",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "taxonomic_lineage",
                    models.TextField(
                        blank=True, db_column="Taxonomic_lineage", null=True
                    ),
                ),
                ("symbol", models.TextField(blank=True, db_column="Symbol", null=True)),
                (
                    "aliases",
                    models.TextField(blank=True, db_column="Aliases", null=True),
                ),
                (
                    "all_gene_name",
                    models.TextField(
                        blank=True, db_column="All_gene\x1f_name", null=True
                    ),
                ),
                (
                    "transcript_protein_name",
                    models.CharField(
                        blank=True,
                        db_column="Transcript_Protein_Name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ensembl_geneids",
                    models.CharField(
                        blank=True,
                        db_column="Ensembl_GeneIDs",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ncbi_gene_id",
                    models.IntegerField(
                        blank=True, db_column="NCBI_gene_ID", null=True
                    ),
                ),
                (
                    "uniprot_id",
                    models.CharField(
                        blank=True, db_column="Uniprot_ID", max_length=255, null=True
                    ),
                ),
                (
                    "kegg_id",
                    models.CharField(
                        blank=True, db_column="KEGG_ID", max_length=255, null=True
                    ),
                ),
                (
                    "kegg_pathway",
                    models.TextField(blank=True, db_column="KEGG_pathway", null=True),
                ),
                (
                    "cellular_component",
                    models.TextField(
                        blank=True, db_column="Cellular_component", null=True
                    ),
                ),
                (
                    "biological_process",
                    models.TextField(
                        blank=True, db_column="Biological_process", null=True
                    ),
                ),
                (
                    "molecular_function",
                    models.TextField(
                        blank=True, db_column="Molecular_function", null=True
                    ),
                ),
                (
                    "pfam_id",
                    models.CharField(
                        blank=True, db_column="Pfam_ID", max_length=255, null=True
                    ),
                ),
                (
                    "protein_function",
                    models.TextField(
                        blank=True, db_column="Protein_Function", null=True
                    ),
                ),
                (
                    "string",
                    models.CharField(
                        blank=True, db_column="String", max_length=255, null=True
                    ),
                ),
                (
                    "alphafolddb",
                    models.CharField(
                        blank=True, db_column="AlphaFoldDB", max_length=255, null=True
                    ),
                ),
                ("pdb", models.TextField(blank=True, db_column="PDB", null=True)),
                (
                    "prosite",
                    models.CharField(
                        blank=True, db_column="PROSITE", max_length=255, null=True
                    ),
                ),
                (
                    "interpro",
                    models.TextField(blank=True, db_column="InterPro", null=True),
                ),
                (
                    "panther",
                    models.CharField(
                        blank=True, db_column="PANTHER", max_length=255, null=True
                    ),
                ),
                ("cdd", models.TextField(blank=True, db_column="CDD", null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True, db_column="Source", max_length=255, null=True
                    ),
                ),
                (
                    "pathway",
                    models.TextField(blank=True, db_column="Pathway", null=True),
                ),
                (
                    "animal_growth",
                    models.CharField(
                        blank=True, db_column="Animal_growth", max_length=255, null=True
                    ),
                ),
                (
                    "disease",
                    models.CharField(
                        blank=True, db_column="Disease", max_length=255, null=True
                    ),
                ),
                (
                    "plant_growth",
                    models.CharField(
                        blank=True, db_column="Plant_Growth", max_length=255, null=True
                    ),
                ),
                (
                    "stress",
                    models.CharField(
                        blank=True, db_column="Stress", max_length=255, null=True
                    ),
                ),
                (
                    "orthology",
                    models.TextField(blank=True, db_column="Orthology", null=True),
                ),
            ],
            options={
                "db_table": "alldata",
            },
        ),
    ]
